# Generated by Django 4.2.1 on 2023-05-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='вопрос',
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(default='text', max_length=300, verbose_name='вопрос'),
            preserve_default=False,
        ),
    ]
