# Generated by Django 3.2.5 on 2023-05-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0002_remove_question_вопрос_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.CharField(default='old', max_length=100),
            preserve_default=False,
        ),
    ]
