# Generated by Django 4.2.1 on 2023-06-10 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('know_me', '0004_auto_20230601_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='know_me.tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='know_me.tag', verbose_name='tag'),
        ),
    ]
